blank_issues_enabled: true
contact_links:
  - name: Donate €5 or more via Open Collective
    url: https://opencollective.com/kiwitcms#section-contribute
    about: Support our open source bounty program
